disable mac for now, need to create an image

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,8 +2,8 @@ name: Build On Changes
 
 on: [push, pull_request]
 
-env:
-  BASE_URL: https://gitlab.sac-home.org/sac-group/sac-packages/-/raw/master/latest/weekly
+# env:
+#   BASE_URL: https://gitlab.sac-home.org/sac-group/sac-packages/-/raw/master/latest/weekly
 
 jobs:
   build-ubuntu:
@@ -19,80 +19,80 @@ jobs:
       - name: Build
         run: make
 
-  build-macos-x86:
-    runs-on: macos-13
-    steps:
-      - name: Get HEAD and submodules
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          submodules: 'recursive'
-      - name: Install sac2c-basic
-        run: |
-          wget ${BASE_URL}/MacOS_x86/sac2c-basic.pkg
-          sudo installer -pkg ./sac2c-basic.pkg -target /
-          sac2c -V
-      - name: Install stdlib-basic
-        run: |
-          wget ${BASE_URL}/MacOS_x86/stdlib-basic.pkg
-          sudo installer -pkg ./stdlib-basic.pkg -target /
-      - name: Create build dir
-        run: |
-          cmake -E make_directory ${{runner.workspace}}/build
-          mkdir $HOME/.sac2crc
-      - name: Set XCode version
-        uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: '14.2'
-      - name: Configure build-system
-        shell: bash
-        working-directory: ${{runner.workspace}}/build
-        run: cmake -DFULLTYPES=ON ${GITHUB_WORKSPACE}
-      - name: Build
-        shell: bash
-        working-directory: ${{runner.workspace}}/build
-        run: |
-          cmake --build . -j 4 2>&1 | tee build.log
-          if [ ${PIPESTATUS[0]} -ne 0 ]; then
-            echo "!!! ERROR detected in build !!!";
-            exit 1;
-          fi
+  # build-macos-x86:
+  #   runs-on: macos-13
+  #   steps:
+  #     - name: Get HEAD and submodules
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #         submodules: 'recursive'
+  #     - name: Install sac2c-basic
+  #       run: |
+  #         wget ${BASE_URL}/MacOS_x86/sac2c-basic.pkg
+  #         sudo installer -pkg ./sac2c-basic.pkg -target /
+  #         sac2c -V
+  #     - name: Install stdlib-basic
+  #       run: |
+  #         wget ${BASE_URL}/MacOS_x86/stdlib-basic.pkg
+  #         sudo installer -pkg ./stdlib-basic.pkg -target /
+  #     - name: Create build dir
+  #       run: |
+  #         cmake -E make_directory ${{runner.workspace}}/build
+  #         mkdir $HOME/.sac2crc
+  #     - name: Set XCode version
+  #       uses: maxim-lobanov/setup-xcode@v1
+  #       with:
+  #         xcode-version: '14.2'
+  #     - name: Configure build-system
+  #       shell: bash
+  #       working-directory: ${{runner.workspace}}/build
+  #       run: cmake -DFULLTYPES=ON ${GITHUB_WORKSPACE}
+  #     - name: Build
+  #       shell: bash
+  #       working-directory: ${{runner.workspace}}/build
+  #       run: |
+  #         cmake --build . -j 4 2>&1 | tee build.log
+  #         if [ ${PIPESTATUS[0]} -ne 0 ]; then
+  #           echo "!!! ERROR detected in build !!!";
+  #           exit 1;
+  #         fi
 
-  build-macos-arm:
-    runs-on: macos-15
-    steps:
-      - name: Get HEAD and submodules
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          submodules: 'recursive'
-      - name: Install sac2c-basic
-        run: |
-          wget ${BASE_URL}/MacOS_arm64/sac2c-basic.pkg
-          sudo installer -pkg ./sac2c-basic.pkg -target /
-          sac2c -V
-      - name: Install stdlib-basic
-        run: |
-          wget ${BASE_URL}/MacOS_arm64/stdlib-basic.pkg
-          sudo installer -pkg ./stdlib-basic.pkg -target /
-      - name: Create build dir
-        run: |
-          cmake -E make_directory ${{runner.workspace}}/build
-          mkdir $HOME/.sac2crc
-      - name: Set XCode version
-        uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: '16.2'
-      - name: Configure build-system
-        shell: bash
-        working-directory: ${{runner.workspace}}/build
-        run: cmake -DFULLTYPES=ON ${GITHUB_WORKSPACE}
-      - name: Build
-        shell: bash
-        working-directory: ${{runner.workspace}}/build
-        run: |
-          cmake --build . -j 3 2>&1 | tee build.log
-          if [ ${PIPESTATUS[0]} -ne 0 ]; then
-            echo "!!! ERROR detected in build !!!";
-            exit 1;
-          fi
+  # build-macos-arm:
+  #   runs-on: macos-15
+  #   steps:
+  #     - name: Get HEAD and submodules
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #         submodules: 'recursive'
+  #     - name: Install sac2c-basic
+  #       run: |
+  #         wget ${BASE_URL}/MacOS_arm64/sac2c-basic.pkg
+  #         sudo installer -pkg ./sac2c-basic.pkg -target /
+  #         sac2c -V
+  #     - name: Install stdlib-basic
+  #       run: |
+  #         wget ${BASE_URL}/MacOS_arm64/stdlib-basic.pkg
+  #         sudo installer -pkg ./stdlib-basic.pkg -target /
+  #     - name: Create build dir
+  #       run: |
+  #         cmake -E make_directory ${{runner.workspace}}/build
+  #         mkdir $HOME/.sac2crc
+  #     - name: Set XCode version
+  #       uses: maxim-lobanov/setup-xcode@v1
+  #       with:
+  #         xcode-version: '16.2'
+  #     - name: Configure build-system
+  #       shell: bash
+  #       working-directory: ${{runner.workspace}}/build
+  #       run: cmake -DFULLTYPES=ON ${GITHUB_WORKSPACE}
+  #     - name: Build
+  #       shell: bash
+  #       working-directory: ${{runner.workspace}}/build
+  #       run: |
+  #         cmake --build . -j 3 2>&1 | tee build.log
+  #         if [ ${PIPESTATUS[0]} -ne 0 ]; then
+  #           echo "!!! ERROR detected in build !!!";
+  #           exit 1;
+  #         fi
